version: "3"

services:
  phpipam:
    container_name: phpipam
    image: arogarth/phpipam
    build: .
    ports:
      - 8080:80
    env_file: database.env
  mysql:
    container_name: mysql
    image: mariadb
    env_file: database.env

